name: Accessor-test

on:
  workflow_dispatch:

jobs:
  accessor-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: test
        uses: ./
        with:
          url: 'https://bili-track.vercel.app/api/cron-data?key=trigger-by-vercel'
